export const DRONE_SIMULATION_HOVER_START_DELAY_MS = 600
export const DRONE_SIMULATION_HOVER_LOOP_DURATION_RANGE_MS = {
  min: 3200,
  max: 5200,
}
export const DRONE_SIMULATION_PREVIEW_HOVER_LOOP_DURATION_RANGE_MS = {
  min: 5600,
  max: 8600,
}
export const DRONE_SIMULATION_ONE_SHOT_DURATION_RANGE_MS = {
  min: 6200,
  max: 9800,
}
export const DRONE_SIMULATION_PREVIEW_ONE_SHOT_DURATION_RANGE_MS = {
  min: 9800,
  max: 15200,
}
export const DRONE_SIMULATION_SEGMENT_ACCELERATION_RATIO = 0.15
export const DRONE_SIMULATION_SEGMENT_DECELERATION_RATIO = 0.15
export const DRONE_SIMULATION_SHARP_TURN_THRESHOLD_DEG = 60
export const DRONE_SIMULATION_SOFT_TURN_THRESHOLD_DEG = 15
export const DRONE_SIMULATION_FOLLOW_RESUME_DELAY_MS = 2000
export const DRONE_SIMULATION_LONG_PATH_WAYPOINT_THRESHOLD = 50
export const DRONE_SIMULATION_TRAIL_POINT_LIMIT = 30
export const DRONE_SIMULATION_TRAIL_POINT_LIMIT_LONG_PATH = 20
export const DRONE_SIMULATION_ACTION_PAUSE_CAP_MS = 2000
export const DRONE_SIMULATION_RESTART_DELAY_MS = 400
export const DRONE_SIMULATION_CAMERA_MIN_DISTANCE = 92
export const DRONE_SIMULATION_CAMERA_MAX_DISTANCE = 184
export const DRONE_SIMULATION_CAMERA_MIN_POLAR_ANGLE = 0.62
export const DRONE_SIMULATION_CAMERA_MAX_POLAR_ANGLE = 0.98
export const DRONE_SIMULATION_CAMERA_DESIRED_POLAR_ANGLE = 0.8
export const DRONE_SIMULATION_CAMERA_DESIRED_FOV = 39
export const DRONE_SIMULATION_CAMERA_TARGET_LERP_SPEED = 4.2
export const DRONE_SIMULATION_CAMERA_POSITION_LERP_SPEED = 2.8
export const DRONE_SIMULATION_CAMERA_RECOVERY_LERP_SPEED = 5.1
export const DRONE_SIMULATION_PREVIEW_CAMERA_POSITION = [122.5, 164.55, 184.36] as const
export const DRONE_SIMULATION_PREVIEW_CAMERA_TARGET = [-1.47, 50, 5.3] as const
export const DRONE_SIMULATION_PREVIEW_CAMERA_FOV = 34
